apps/blog/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    nickname = db.Column(db.String, unique=True, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    created_at = db.Column(db.DateTime, default=datetime.now)

    # 비밀번호 프로퍼티와 관련 메서드
    @property
    def password(self):
        raise AttributeError("읽어들일 수 없음")
    
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 비밀번호 검증 메서드
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    # 중복 검사 메서드
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None
    
    def is_duplicate_nickname(self):
        return User.query.filter_by(nickname=self.nickname).first() is not None

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, index=True)
    content = db.Column(db.String, index=True)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

apps/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, DateTimeField
from wtforms.validators import DataRequired
from datetime import datetime

class PostForm(FlaskForm):
    title = StringField(
        "제목",
        validators=[
            DataRequired(message = "제목을 작성해주세요.")
        ]
    )
    content = TextAreaField(
        "내용",
        validators=[
            DataRequired(message = "내용을 입력해주세요.")
        ]
    )
    created_at = DateTimeField("생성일", default=datetime.now)
    updated_at = DateTimeField("업데이트일", default=datetime.now)
    submit = SubmitField("등록")

apps/blog/__init__.py
import apps.blog.models

apps/blog/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from apps.blog.forms import PostForm
from apps.app import db
from apps.blog.models import Post
from flask_login import login_required

blog = Blueprint(
    "blog",
    __name__,
    template_folder="templates",
    static_folder="static"
)

# 페이징 기능 넣기 전
# @blog.route("/post")
# def post():
#     posts = Post.query.all()
#     page = request.args.get('page', type=int, default=1)
#     posts = posts.paginate(page=page, per_page=2)
#     for post in posts :
#         post.content = post.content.replace('\n', '<br>')

@blog.route("/post")
def post():
    page = request.args.get('page', type=int, default=1)

    # 게시물을 가져오는 쿼리 
    posts_query = Post.query.order_by(Post.created_at.desc())

    # 게시물을 페이징하여 가져오기
    posts_paginated = posts_query.paginate(page=page, per_page=9)

    return render_template("blog/post.html", posts=posts_paginated)

@blog.route('/post/detail/<post_id>')
def detail(post_id):
    post = Post.query.get(post_id)
    post.content = post.content.replace('\n', '<br>')
    return render_template('blog/detail_post.html', post=post)

@blog.route("/post/new", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()

    # 폼 유효성 검사 및 데이터 처리
    if form.validate_on_submit():
        post = Post(
            title = form.title.data,
            content = form.content.data
        )

        db.session.add(post)
        db.session.commit()

        return redirect(url_for("blog.post"))
    return render_template("blog/create_post.html", form=form, title="게시물 작성")

@blog.route("/post/edit/<post_id>", methods=["GET", "POST"])
@login_required
def edit_post(post_id):
    form = PostForm()

    # 기존 게시물 조회
    post = Post.query.filter_by(id=post_id).first()

    # 폼 유효성 검사 및 데이터 처리
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.updated_at = form.updated_at.data
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("blog.post"))
    return render_template("blog/edit.html", post=post, form=form, title="게시물 수정")

@blog.route("/post/<post_id>/delete", methods=["GET", "POST"])
@login_required
def delete_post(post_id):
    post = Post.query.filter_by(id=post_id).first()
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("blog.post"))

# 일명 관리자모드..?
# @blog.route("/users")
# def users():
#     users = User.query.all()
#     return render_template("blog/users.html", users=users)

# @blog.route("/users/<user_id>", methods=["GET", "POST"])
# def edit_user(user_id):
#     form = UserForm()
#     user = User.query.filter_by(id=user_id).first()
#     if form.validate_on_submit():
#         user.nickname = form.nickname.data
#         user.email = form.email.data
#         user.password = form.password.data
#         db.session.add(user)
#         db.session.commit()
#         return redirect(url_for("blog.post"))
#     return render_template("blog/edit_user.html", user=user, form=form, title="회원정보 수정")

# @blog.route("/users/<user_id>/delete", methods=["POST"])
# def delete_user(user_id):
#     user=User.query.filter_by(id=user_id).first()
#     db.session.delete(user)
#     db.session.commit()
#     return redirect(url_for("blog.post"))

apps/blog/templates/blog/create_post.html
{% extends 'blog/layout.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('blog.static', filename='create-post.css') }}">
<div class="write-post">
    <form
        action="{{ url_for('blog.create_post') }}"
        method="post"
        novalidate="novalidate">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.title(class="form-control", id="title", placeholder="제목") }}
        </div>
        <div class="form-group">
            {{ form.content(class="form-control", id="content") }}
        </div>
        <button type="submit" class="btn">작성하기</button>
    </form>
</div>
{% endblock %}

apps/blog/templates/blog/detail_post.html
{% extends 'blog/layout.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('blog.static', filename='post.css') }}">
<div class="post">
    <div class="post-title">
        <h1>{{ post.title }}</h1>
        <hr>
    </div>
    <div class="post-content">
        <p id="post-content">
            {% autoescape false %}
            {{ post.content }}
            {% endautoescape %}
        </p>
        {% if post.updated_at == post.created_at %}
            <p class="post-date">{{ post.created_at.strftime("%Y-%m-%d %I:%M %p") }}</p>
        {% else %}
            <p class="post-date">{{ post.updated_at.strftime("%Y-%m-%d %I:%M %p") }}</p>
        {% endif %}
        <div class="post-buttons">
            <a href="{{ url_for('blog.edit_post', post_id=post.id) }}" class="edit-button">수정</a>
            <a href="{{ url_for('blog.delete_post', post_id=post.id) }}" class="delete-button"
            onclick="return confirm('게시물을 삭제하시겠습니까?')">삭제</a>
        </div>
</div>
{% endblock %}

apps/blog/templates/blog/edit.html
{% extends 'blog/layout.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('blog.static', filename='create-post.css') }}">
<div class="write-post">
    <form
        action="{{ url_for('blog.edit_post', post_id=post.id) }}"
        method="post"
        novalidate="novalidate">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.title(class="form-control", id="title", placeholder="제목", value=post.title) }}
        </div>
        <div class="form-group">
            <textarea class="form-control" id="content" name="content">{{ post.content }}</textarea>
        </div>
        <button type="submit" class="btn">수정</button>
    </form>
</div>
{% endblock %}

apps/blog/templates/blog/edit_user.html
{% extends 'blog/layout.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('blog.static', filename='edit_user.css') }}">
<div class="table" style="margin-top: 50px;">
    <form action="{{ url_for('blog.edit_user', user_id=user.id) }}"
        method="post"
        novalidate="novalidate"
        id="editForm"
        autocomplete="off">
        {{ form.csrf_token }}
        <h2>회원정보 수정</h2>
        <p>
            {{ form.nickname(value=user.nickname) }}
        </p>
        <p>
            {{ form.email(value=user.email)}}
        </p>
        <p>
            {{ form.password(placeholder="비밀번호") }}
        </p>
        <input type="submit" value="수정">
        <button type="button" id="deleteButton">회원탈퇴</button>
    </form>
</div>

<script>
    document.getElementById('deleteButton').addEventListener('click', function(event) {
        let confirmation = confirm('회원을 탈퇴하시겠습니까?');
        if (confirmation) {
            let deleteForm = document.createElement('form');
            deleteForm.action = "{{ url_for('blog.delete_user', user_id=user.id) }}";
            deleteForm.method = 'post';

            let csrfTokenInput = document.createElement('input');
            csrfTokenInput.type = 'hidden';
            csrfTokenInput.name = 'csrf_token';
            csrfTokenInput.value = "{{ form.csrf_token._value() }}";
            deleteForm.appendChild(csrfTokenInput);

            document.body.appendChild(deleteForm);
            deleteForm.submit();
        }
    });
</script>
{% endblock %}

apps/blog/templates/blog/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='layout.css') }}">
    <script src="{{ url_for('auth.static', filename='logout.js') }}"></script>
    {% if title %}
    <title>Board - {{ title }}</title>
    {% else %}
    <title>Board</title>
    {% endif %}
</head>
<body>
    <div class="top-bar">
        <div class="title">
            <span>Board</span>
        </div>
        <div class="home">
            <a href="{{ url_for('blog.post') }}">Home</a>
        </div>
        <div class="write">
        <a href="{{ url_for('blog.create_post') }}">글쓰기</a>
        </div>
        <div class="login">
            <a>
            {% if current_user.is_authenticated %}
            <a id="nick" href="{{ url_for('auth.edit_user', user_id=current_user.id) }}">{{ current_user.nickname }}</a> 님
                <span><a href="{{ url_for('auth.logout') }}">Logout</a></span>
            {% else %}
                <span><a href="{{ url_for('auth.login') }}">Login</a></span>
            {% endif %}
            </a>
        </div>
    </div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

apps/blog/templates/blog/post.html
{% extends 'blog/layout.html' %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('blog.static', filename='post.css') }}">
<link rel="stylesheet" href="{{ url_for('blog.static', filename='page.css') }}">
{% for post in posts.items %}
<div class="post" id="main_post">
    <div class="post-title">
        <h1><a class="main_title" href="{{ url_for('blog.detail', post_id=post.id) }}">{{ post.title | truncate(30)}}</a></h1>
    </div>
</div>
{% endfor %}
<div class="pagination">
    <ul>
        <!-- 이전 페이지 -->
        {% if posts.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">이전</span>
        </li>
        {% endif %}
        
        <!-- 페이지 번호 -->
        {% for page_num in posts.iter_pages() %}
        {% if page_num %}
        {% if page_num == posts.page %}
        <li class="page-item active">
            <span class="page-link">{{ page_num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">...</span>
        </li>
        {% endif %}
        {% endfor %}
        
        <!-- 다음 페이지 -->
        {% if posts.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ posts.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">다음</span>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

apps/blog/templates/blog/users.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('blog.static', filename='users.css')}}">
</head>
<body>
    <table>
        <tr>
            <th>사용자 NUM</th>
            <th>닉네임</th>
            <th>이메일</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>
                <a href="{{ url_for('blog.edit_user', user_id=user.id)}}">
                    {{ user.id }}
                </a></td>
            <td>{{ user.nickname }}</td>
            <td>{{ user.email }}</td> 
        </tr>
        {% endfor %}
    </table>
</body>
</html> -->